name: "Master CI/CD"
run-name: "Master CI/CD runned by: ${{ github.actor}}"

on:
  push:
    branches:
      - "main"
  pull_request:
    types: [opened, ready_for_review]
  workflow_dispatch:
    inputs:
      branch:
        description: "Branch Name"
        default: "main"
        required: true
      logLevel:
        description: "Log level"
        required: true
        default: "warning"
        type: choice
        options:
          - info
          - warning
          - debug
      tags:
        description: "Test scenario tags"
        required: false
        type: boolean

jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: First Step
        run: echo "Runned by ${{github.actor}}"

      - name: Values
        run: echo "${{inputs.branch}} ${{ inputs.logLevel }} ${{inputs.tags}}"
