name: "Master CI/CD"
run-name: "Master CI/CD runned by: ${{ github.actor}}"

on:
  # schedule:
  #   - cron: "*/10 * * * *"
  push:
    branches:
      - "main"
  pull_request:
    types: [opened, ready_for_review]
  workflow_dispatch:
    inputs:
      branch:
        description: "Branch Name"
        default: "main"
        required: true
      logLevel:
        description: "Log level"
        required: true
        default: "warning"
        type: choice
        options:
          - info
          - warning
          - debug
      tags:
        description: "Test scenario tags"
        required: false
        type: boolean
  issue_comment:
    types: [created]      

jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: First Step
        run: echo "Runned by ${{github.actor}}"
      
      - name: List repo files
        run: ls    

      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          ref: 'main'
          
      - name: List repo files
        run: ls    
      
  # pr_commented:
  #   name: PR comment
  #   if: ${{ github.event.issue.pull_request }}
  #   runs-on: ubuntu-latest
  #   steps:
  #     - run: |
  #         echo A comment on PR $NUMBER
  #       env:
  #         NUMBER: ${{ github.event.issue.number }}
  
  # second-workflow:
  #   uses: ./.github/workflows/master-ci-cd-second.yml
  #   with:
  #     branch: 'main'
  #     logLevel: 'error'          