name: "Master CI/CD"
run-name: "Master CI/CD runned by: ${{ github.actor}}"

on:
  push:
    branches: 
            - "main"

jobs:
    first-job:
        runs-on: ubuntu-latest
        steps:
            - name: "Greeting"
              run: echo "My name is ${{github.actor}}"  
    
    first-second-job:
      runs-on: ubuntu-latest
      needs: [first-job]
      steps:
          - name: "Greeting"
            run: echo "My name is ${{github.actor}}"  
    
    second-job:
      runs-on: ubuntu-latest
      steps:
          - name: "Greeting"
            run: echo "My name is ${{github.actor}}"    
                      
    third-job:
      runs-on: ubuntu-latest
      steps:
          - name: "Greeting"
            run: echo "My name is ${{github.actor}}"            