name: "Master CI/CD"
run-name: "Master CI/CD runned by: ${{ github.actor}}"

on:
  push:
    branches: 
            - "main"

jobs:
    very-first-job:
      runs-on: ubuntu-latest
      steps:
          - name: "Greeting"
            run: echo "My name is ${{github.actor}}" 
            
          - name: "Bye"
            run: echo "Bye"  

    first-job:
      needs: [very-first-job]
      runs-on: ubuntu-latest
      steps:
          - name: "Greeting"
            run: echo "My name is ${{github.actor}}" 
            
          - name: "Bye"
            run: echo "Bye"  
    part-first-job:
      runs-on: ubuntu-latest
      needs: [first-job]
      steps:
          - name: "Greeting"
            run: echo "My name is ${{github.actor}}"         

    second-job:
      runs-on: ubuntu-latest
      steps:
        - name: "Greeting"
          run: echo "My name is ${{github.actor}}" 
          
        - name: "Second"
          run: echo "Second"  

        - name: "Last"
          run: echo "Last"    
                  
    third-job:
      runs-on: ubuntu-latest
      steps:
        - name: "Greeting"
          run: echo "My name is ${{github.actor}}"  

    part-second-job:
      runs-on: ubuntu-latest
      needs: [first-job,second-job,third-job]
      steps:
          - name: "Greeting"
            run: echo "My name is ${{github.actor}}"           


    last-job:
      runs-on: ubuntu-latest
      needs: [part-second-job]
      steps:
          - name: "Greeting"
            run: echo "My name is ${{github.actor}}"                   

    very-last-job:
      runs-on: ubuntu-latest
      needs: [part-second-job,first-job,second-job,third-job]
      steps:
          - name: "Greeting"
            run: echo "My name is ${{github.actor}}"                           